cursor #e6e1e9
cursor_text_color #cac4cf

foreground            #e6e1e9
background            #141318
selection_foreground  #322e41
selection_background  #cbc3dc
url_color             #cdbdff

color0   #141318
color1   #ff7290
color2   #7fff99
color3   #ffd972
color4   #b9a7f2
color5   #4b3e76
color6   #cdbdff
color7   #f3efff
color8   #9c99a5
color9   #ff9fb3
color10  #a5ffb8
color11  #ffe7a5
color12  #d4c6ff
color13  #dbd0ff
color14  #e8e1ff
color15  #faf8ff
